# -*- coding: utf-8 -*-
"""14 Aug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiycZCL3pYQn9IjTJjeQ86BrbKZv7Z1s
"""

def unitary_sum_ofdigits(n):
    while n >=10:
        sum_of_digit=0

        while n>0:
         sum_of_digit+=n%10
         n=n//10
        n=sum_of_digit
    return n

unitary_sum_ofdigits(231)

def compressed_string(s):
    if not s:
        return ""

    temp_string = ""
    count = 1
    n = len(s)

    for i in range(n - 1):
        if s[i] == s[i + 1]:
            count += 1
        else:
            temp_string += s[i] + str(count)
            count = 1

    temp_string += s[-1] + str(count)

    return temp_string

compressed_string("aaabbcsss")